### ISSUE TITLE
Make tests deterministic

### ISSUE THREAD

**Issue by inejc** [picnicml/doddle-model#15]
Integration tests fail sometimes as data is shuffled without a seed.

**Comment by novoselrok** [comment]
Hey, I'd be willing to help you out on this :) Do you have any extra information before I can start?

**Comment by novoselrok** [comment]
I think the current version (`0.13.2.`) of breeze does not support shuffling with random generators with seed. It was added in version `1.0-RC2` (https://github.com/scalanlp/breeze/commit/92cc09c3bdf9952cfbbdbb72d7afae5c4bf91421) with the implicit RandBasis parameter.

**Comment by inejc** [comment]
You are right. Given that only indices are shuffled, it should be possible to simply use `scala.util.Random.shuffle` and make seed an implicit parameter to `cv.score()`.

**Comment by novoselrok** [comment]
Maybe instead of passing just the seed, we can pass the whole `Random` object like: `(implicit rnd: scala.util.Random = new scala.util.Random())`? Or maybe specify the seed when creating the object, like `randomState` in `scikit-learn`?

**Comment by inejc** [comment]
Passing the `Random` object implicitly seems even better. I think this ensures that some particular seed (or instance of `Random`) is only used in functions that take implicit `Random` (in our case cross-validation).
