### ISSUE TITLE
Create a Github page for Picnic Machine Learning

### ISSUE THREAD

**Issue by inejc** [picnicml/doddle-model#20]
Create a single page website: `picnicml.github.io`.

**Comment by munirozkul** [comment]
I can help you 😉👍

**Comment by inejc** [comment]
Hey @munirozkul. That's great, thanks! I've created a repo: https://github.com/picnicml/picnicml.github.io. I was thinking of something minimalistic with a title **Picnic Machine Learning**, an additional label **Immutable machine learning in Scala.** and a link to the [doddle-model](https://github.com/picnicml/doddle-model) repo. What do you think?

**Comment by munirozkul** [comment]
Ok, cool;) 

Let me fork your [picnicml.github.io](https://github.com/picnicml/picnicml.github.io) repo and try something to show you.

**Comment by inejc** [comment]
That sounds great, thanks :).

**Comment by munirozkul** [comment]
Yes, here is an example:
https://munirozkul.github.io/picnicml.github.io/

**Comment by inejc** [comment]
What do you think about centering everything that's on a white background and making the github icon bigger? Nitpicking, but `<title>PicnicML</title>` should probably be `<title>picnicml</title>`.

**Comment by munirozkul** [comment]
Of course;) Let me try..

**Comment by munirozkul** [comment]
Here it is: https://munirozkul.github.io/picnicml.github.io/

**Comment by inejc** [comment]
Thanks, @munirozkul. I've discussed this with @novoselrok and we'll take a different approach for GH pages. The main difference is that we'll add documentation automatically generated from scaladoc. Nevertheless, we appreciate your contribution, if you are still willing to help, LMK :D.

**Comment by munirozkul** [comment]
No, thanks. Bye
